
###
GET http://localhost:3000

###
GET http://localhost:3000/songs

###
GET http://localhost:3000/songs/cf

###
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title" : "Lasting Lover",
    "artists" : ["Sigla"],
    "releasedDate" : "2022-09-29",
    "duration" : "02:34"
}

###
DELETE http://localhost:3000/songs/1

###
PUT http://localhost:3000/songs/1













